#+AUTHOR: Alex Lu
#+EMAIL: alexluigit@gmail.com
#+startup: content

* =listing directory failed but ‘access-file’ worked= error on macOS

1. Install =gls= (GNU ls) from GNU coreutils

#+begin_src bash
  brew install coreutils
#+end_src

2. Set ~insert-directory-program~ to =gls=

#+begin_src emacs-lisp
  (setq insert-directory-program "gls")
#+end_src

* How to hide the parent directory?

#+begin_src emacs-lisp
(setq dirvish-default-layout '(0 0.4 0.6))
#+end_src

* How to startup dirvish without preview and parent windows?


#+begin_src emacs-lisp
;; consult its docstring for more info
(setq dirvish-default-layout nil)
#+end_src

* How to kill all session buffers on quit?

Set ~dirvish-reuse-session~ to nil.

* Dirvish does not respect listing switches?

See [[file:CUSTOMIZING.org][Parsing switches]] and [[file:CUSTOMIZING.org][sample config]].

* Why do I have duplicate icon columns?

Disable =all-the-icons-dired= and =treemacs-icons-dired=.

* Can not get access to commands in =dirvish-mode-map=?

It happend for some =evil-mode= users, you can try [[https://github.com/alexluigit/dirvish/issues/188][this]]:

#+begin_src emacs-lisp
;; setting it after dirvish to ensure `dirvish-mode-map' is loaded
(evil-make-overriding-map dirvish-mode-map 'normal)
#+end_src

* Directory (Dired) previews not displayed in the preview buffer

It could happen if you enabled ~global-nlinum-mode~, disable them in the directory
preview buffers should do the trick: [[https://github.com/alexluigit/dirvish/issues/306][#306]]

#+begin_src emacs-lisp
(add-hook 'dirvish-directory-view-mode-hook (lambda () (nlinum-mode 0)))
#+end_src
